@startuml
left to right direction

title "Development and Evaluation in PoC stage"

node "Dev Environment" {

[Data Generator] as datagen

[CustomAlgo (PoC)] as algo #orange

[Evaluation] as eval

datagen --> algo
algo --> eval
}
@enduml